name: iOS build

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 

      - name: Set up build environment
        uses: actions/checkout@v2

      - name: building
        run: | 
              apt-get install build-essential
              chmod +x ./build.sh
              ./build.sh
       
      
      - name: checking directories
        run: ls
