name: linux build

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 

      - name: Set up build environment
        uses: actions/checkout@v2

      - name: building
        run: |
              chmod +x ./build.sh
              ./build.sh
       
      
      - name: checking directories
        run: |
             cd "enet server test"
             ls
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: GrowtopiaServer
          path: "enet server test/enet server test"
             
