name: iOS build

on:
  [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up build environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10.3.0'
         
       

      - name: Set up build environment pt. II
        uses: actions/checkout@v2

      - name: Set up build environment pt. III
        run: apt-get install build-essential


      - name: building
        run: | 
              chmod +x ./build.sh
              ./build.sh
          
            
     
      
      - name: checking directories
        run: ls
